chore: Check linking

diff --git a/.build/docker/Dockerfile b/.build/docker/Dockerfile
--- a/.build/docker/Dockerfile
+++ b/.build/docker/Dockerfile
@@ -12,6 +12,9 @@ RUN bun install
 RUN bun run build:node
 RUN ls -la /app/build
 
+RUN ldd ./build/seda-overlay-linux-x64 || echo "ldd failed"
+
+
 RUN ./build/seda-overlay-linux-x64 init --network testnet
 
 ENTRYPOINT ["./build/seda-overlay-linux-x64"]
